// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "xueyouchen",
            "email": "xueyou@starboardventures.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ping": {
            "get": {
                "description": "Healthy examination",
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Sys"
                ],
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error:...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/network_core/circulating-supply/circulating_supply": {
            "get": {
                "description": "List table circulating_supply",
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "DATA-INFRA-API-External-V1"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2022-07-01",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2022-06-01",
                        "name": "start_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/busi.CirculatingSupply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ResponseWithRequestId"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ResponseWithRequestId"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "busi.CirculatingSupply": {
            "type": "object",
            "properties": {
                "burnt_fil": {
                    "type": "number"
                },
                "burnt_fil_increase": {
                    "type": "number"
                },
                "circulating_fil": {
                    "type": "number"
                },
                "circulating_fil_increase": {
                    "type": "number"
                },
                "locked_fil": {
                    "type": "number"
                },
                "locked_fil_increase": {
                    "type": "number"
                },
                "mined_fil": {
                    "type": "number"
                },
                "mined_fil_increase": {
                    "type": "number"
                },
                "reserve_disbursed_fil": {
                    "type": "number"
                },
                "reserve_disbursed_fil_increase": {
                    "type": "number"
                },
                "stat_date": {
                    "type": "string"
                },
                "vested_fil": {
                    "type": "number"
                },
                "vested_fil_increase": {
                    "type": "number"
                }
            }
        },
        "utils.ResponseWithRequestId": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "block-api.spacescope.io",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "api server",
	Description:      "spacescope block explorer api server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
