basePath: /api/v1
definitions:
  busi.EVMContractVerify:
    properties:
      address:
        type: string
      compiler_type:
        type: integer
      compiler_version:
        type: string
      contract_name:
        type: string
      create_at:
        type: string
      id:
        type: integer
      license_type:
        type: string
      status:
        type: integer
      updated_at:
        type: string
    type: object
  busi.EVMInternalTX:
    properties:
      from:
        type: string
      hash:
        type: string
      height:
        type: integer
      parent_hash:
        type: string
      to:
        type: string
      type:
        type: integer
      value:
        type: string
      version:
        type: integer
    type: object
  busi.EVMTransaction:
    properties:
      block_hash:
        type: string
      block_number:
        type: integer
      chain_id:
        type: integer
      from:
        type: string
      gas:
        type: integer
      gas_limit:
        type: integer
      hash:
        type: string
      height:
        type: integer
      input:
        type: string
      max_fee_per_gas:
        type: string
      max_priority_fee_per_gas:
        type: string
      nonce:
        type: integer
      r:
        type: string
      s:
        type: string
      to:
        type: string
      transaction_index:
        type: integer
      type:
        type: integer
      v:
        type: string
      value:
        type: string
      version:
        type: integer
    type: object
  core.CompileVersion:
    properties:
      long_version:
        type: string
      version:
        type: string
    type: object
  core.CompileVersionList:
    properties:
      versions:
        items:
          $ref: '#/definitions/core.CompileVersion'
        type: array
    type: object
  core.Contract:
    properties:
      address:
        type: string
      balance:
        type: string
      compiler:
        type: string
      filecoinAddress:
        type: string
      license:
        type: string
      name:
        type: string
      txns:
        type: integer
      verified:
        type: string
      version:
        type: integer
    type: object
  core.ContractVerify:
    properties:
      abi:
        type: string
      address:
        type: string
      compiler_type:
        type: integer
      compiler_version:
        type: string
      contract_name:
        type: string
      create_at:
        type: string
      err_msg:
        type: string
      id:
        type: integer
      license_type:
        type: string
      source_codes:
        items:
          $ref: '#/definitions/core.SourceCode'
        type: array
      status:
        type: integer
      updated_at:
        type: string
    type: object
  core.SourceCode:
    properties:
      code:
        type: string
      file_name:
        type: string
    type: object
  utils.ResponseWithRequestId:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      request_id:
        type: string
    type: object
host: block-explorer-api.spacescope.io
info:
  contact:
    email: xueyou@starboardventures.io
    name: xueyouchen
  description: spacescope block explorer api server
  termsOfService: http://swagger.io/terms/
  title: api server
  version: "1.0"
paths:
  /api/v1/complieversions:
    get:
      consumes:
      - application/json
      - application/json
      description: list compile version
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.CompileVersionList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contract/{address}:
    get:
      consumes:
      - application/json
      - application/json
      description: Get contract detail
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Contract'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contract/{address}/internal_txns:
    get:
      consumes:
      - application/json
      - application/json
      description: List contract's internal transactions
      parameters:
      - in: query
        name: l
        type: integer
      - in: query
        name: o
        type: integer
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/busi.EVMInternalTX'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contract/{address}/txns:
    get:
      consumes:
      - application/json
      - application/json
      description: List contract's transactions
      parameters:
      - in: query
        name: l
        type: integer
      - in: query
        name: o
        type: integer
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/busi.EVMTransaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contracts:
    get:
      consumes:
      - application/json
      - application/json
      description: List contracts
      parameters:
      - in: query
        name: l
        type: integer
      - in: query
        name: o
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Contract'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contractverify/{address}:
    post:
      consumes:
      - application/json
      - application/json
      description: submit contract verify
      parameters:
      - description: TODO need support more CompilerType, only implement single file
          now.
        enum:
        - 1
        - 2
        - 3
        in: query
        name: compiler_type
        required: true
        type: integer
      - in: query
        name: compiler_version
        required: true
        type: string
      - in: query
        name: evm_version
        type: string
      - in: query
        name: is_optimization
        type: boolean
      - in: query
        name: license_type
        required: true
        type: string
      - description: TODO need more field support more CompilerType
        in: query
        name: runs
        required: true
        type: integer
      - in: query
        name: source_code
        type: string
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/busi.EVMContractVerify'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/contractverify/{id}:
    get:
      consumes:
      - application/json
      - application/json
      description: check contract verify
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.ContractVerify'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseWithRequestId'
      tags:
      - DATA-INFRA-API-External-V1
  /api/v1/ping:
    get:
      consumes:
      - application/json
      - application/json
      description: Healthy examination
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "500":
          description: error:...
          schema:
            type: string
      tags:
      - Sys
swagger: "2.0"
